export const cities = [
  // Madagascar
  'Antananarivo', 'Toamasina', 'Antsirabe', 'Fianarantsoa', 'Mahajanga',
  'Toliara', 'Antsiranana', 'Ambatondrazaka', 'Manakara', 'Morondava',
  'Farafangana', 'Maroantsetra', 'Andoany', 'Ambanja', 'Ambositra',
  'Mananjary', 'Soanierana-Ivongo', 'Vohémar', 'Nosy Be', 'Sambava',
  'Maintirano', 'Ihosy', 'Ampanihy', 'Taolagnaro', 'Manantenina',
  // Afrique
  'Dakar', 'Abidjan', 'Lagos', 'Nairobi', 'Johannesburg', 'Casablanca',
  'Tunis', 'Alger', 'Tripoli', 'Khartoum', 'Addis Ababa', 'Kigali',
  'Bujumbura', 'Kampala', 'Dar es Salaam', 'Maputo', 'Luanda',
  'Windhoek', 'Gaborone', 'Harare', 'Lusaka', 'Lilongwe', 'Blantyre',
  'Accra', 'Kumasi', 'Kinshasa', 'Brazzaville', 'Libreville', 'Yaoundé',
  'Douala', 'Cotonou', 'Lomé', 'Ouagadougou', 'Bamako', 'Nouakchott',
  'Praia', 'Bissau', 'Conakry', 'Freetown', 'Monrovia', 'Port Harcourt',
  // Europe
  'Paris', 'Lyon', 'Marseille', 'Toulouse', 'Nice', 'Nantes', 'Bordeaux',
  'Londres', 'Manchester', 'Liverpool', 'Edinburgh', 'Berlin', 'Munich',
  'Hambourg', 'Cologne', 'Francfort', 'Madrid', 'Barcelone', 'Valence',
  'Séville', 'Rome', 'Milan', 'Naples', 'Turin', 'Florence', 'Venise',
  'Lisbonne', 'Porto', 'Amsterdam', 'Rotterdam', 'Anvers', 'Bruxelles',
  'Vienne', 'Salzbourg', 'Berne', 'Zurich', 'Genève', 'Stockholm',
  'Göteborg', 'Copenhague', 'Oslo', 'Helsinki', 'Dublin', 'Cork',
  'Varsovie', 'Cracovie', 'Prague', 'Budapest', 'Sofia', 'Bucarest',
  'Athènes', 'Thessalonique', 'Belgrade', 'Zagreb', 'Ljubljana',
  'Bratislava', 'Riga', 'Tallinn', 'Vilnius', 'Reykjavik',
  // Amérique du Nord
  'New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia',
  'San Antonio', 'San Diego', 'Dallas', 'Austin', 'Boston', 'Seattle',
  'Denver', 'Washington', 'Miami', 'Atlanta', 'Portland', 'Detroit',
  'Toronto', 'Vancouver', 'Montreal', 'Calgary', 'Ottawa', 'Edmonton',
  'Mexico', 'Guadalajara', 'Monterrey', 'Cancun', 'Puebla',
  // Amérique du Sud
  'São Paulo', 'Rio de Janeiro', 'Brasilia', 'Salvador', 'Fortaleza',
  'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Buenos Aires',
  'Córdoba', 'Mendoza', 'Rosario', 'Santiago', 'Valparaíso', 'Concepcion',
  'Lima', 'Arequipa', 'Bogotá', 'Medellín', 'Cali', 'Cartagena',
  'Caracas', 'Maracaibo', 'Quito', 'Guayaquil', 'La Paz', 'Santa Cruz',
  'Asunción', 'Montevideo', 'Paramaribo', 'Georgetown',
  // Asie
  'Tokyo', 'Osaka', 'Nagoya', 'Sapporo', 'Kyoto', 'Kobe', 'Fukuoka',
  'Shanghai', 'Beijing', 'Shenzhen', 'Guangzhou', 'Chengdu', 'Wuhan',
  'Xi\'an', 'Hong Kong', 'Taipei', 'Kaohsiung', 'Seoul', 'Busan',
  'Incheon', 'Delhi', 'Mumbai', 'Bangalore', 'Chennai', 'Hyderabad',
  'Kolkata', 'Ahmedabad', 'Singapore', 'Kuala Lumpur', 'George Town',
  'Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Bangkok', 'Chiang Mai',
  'Phuket', 'Ho Chi Minh', 'Hanoi', 'Da Nang', 'Manila', 'Cebu City',
  'Davao', 'Dubai', 'Abu Dhabi', 'Sharjah', 'Tel Aviv', 'Jerusalem',
  'Beirut', 'Ankara', 'Istanbul', 'Izmir', 'Riyadh', 'Jeddah', 'Mecca',
  'Tehran', 'Baghdad', 'Kuwait City', 'Doha', 'Muscat', 'Sanaa',
  // Océanie
  'Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Canberra',
  'Gold Coast', 'Newcastle', 'Wollongong', 'Auckland', 'Wellington',
  'Christchurch', 'Hamilton', 'Tauranga', 'Port Moresby', 'Suva',
];